In [1]:
import numpy as  np

In [2]:
fruits = ['apple', 'banana', 'orange']
vegetables = ['lettuce', 'tomato', 'cabbage']

print(fruits)
print(vegetables)

['apple', 'banana', 'orange']
['lettuce', 'tomato', 'cabbage']


In [6]:
fruits_vegetables = np.array([fruits,vegetables])

print(fruits_vegetables)

print('we are making a list out of 2 lists')

print('THIS array is a 2-dimentional table. meaning got rows and column')

[['apple' 'banana' 'orange']
 ['lettuce' 'tomato' 'cabbage']]
we are making a list out of 2 lists
THIS array is a 2-dimentional table. meaning got rows and column


In [22]:
print(fruits_vegetables[0][0])
print(fruits_vegetables[0][1])
print(fruits_vegetables[1][0])
print(fruits_vegetables[0])
print(fruits_vegetables[1])

print('THE INDEX FOLLOWS ROW THEN COLUMN. START WITH 0')

apple
banana
lettuce
['apple' 'banana' 'orange']
['lettuce' 'tomato' 'cabbage']
THE INDEX FOLLOWS ROW THEN COLUMN. START WITH 0


In [14]:
print(type(fruits_vegetables))

<class 'numpy.ndarray'>


In [29]:
fruits_vegetables.ndim


2

In [30]:
print('Tells you the NUMBER OF DIMENSIONS. In this case, this fruits_vegetables is a 2-dimensional array')

Tells you the NUMBER OF DIMENSIONS. In this case, this fruits_vegetables is a 2-dimensional array


In [31]:
fruits_vegetables.shape


(2, 3)

In [32]:
print('Tells you HOW MANY ELEMENTS ARE IN THE DIMENSION. In this case, the array has 2 rows, 3 columns thats why (2,3)')

Tells you HOW MANY ELEMENTS ARE IN THE DIMENSION. In this case, the array has 2 rows, 3 columns thats why (2,3)


In [17]:
fruits_vegetables.size

6

In [33]:
print('Tells you the TOTAL NUMBER OF CELLS in the array')

Tells you the TOTAL NUMBER OF CELLS in the array


In [18]:
fruits_vegetables.dtype

dtype('<U7')

In [43]:
print('This returns the DATA TYPE OF THE ELEMENTS stored in the array. In this case, <U7 refers to strings/mix types with < 7 items.')

This returns the DATA TYPE OF THE ELEMENTS stored in the array. In this case, <U7 refers to strings/mix types with < 7 items.


In [36]:
age_heights = np.array([[25,21,18],[1.82,1.69,1.73]])
age_heights

array([[25.  , 21.  , 18.  ],
       [ 1.82,  1.69,  1.73]])

In [37]:
age_heights.ndim

2

In [38]:
age_heights.shape

(2, 3)

In [39]:
age_heights.size

6

In [40]:
age_heights.dtype

dtype('float64')

In [41]:
print('^ this refers to floating decimal numbers')

^ this refers to floating decimal numbers


In [52]:
age_heights[1]

array([1.82, 1.69, 1.73])

In [57]:
np.mean(age_heights)

np.float64(11.54)

In [58]:
print('this reflects the mean of all elements')

this reflects the mean of all elements


In [56]:
np.mean(age_heights[1,])

np.float64(1.7466666666666668)

In [60]:
print('this reflects the mean of elements in row 1, height')

this reflects the mean of elements in row 1, height


In [63]:
np.mean(age_heights[0,])

np.float64(21.333333333333332)

In [64]:
print('this reflects the mean of elements in row 0, age')

this reflects the mean of elements in row 0, age


## ACTIVITY 1

In [66]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [67]:
data_url = "https://raw.githubusercontent.com/selva86/datasets/refs/heads/master/BostonHousing.csv"

In [71]:
print('This line assigns a URL string to a variable. To actually load the data, use pandas')

This line assigns a URL string to a variable. To actually load the data, use pandas


In [72]:
raw_data = np.genfromtxt(data_url, delimiter=",", skip_header=1)

print(raw_data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 3.9690e+02 4.9800e+00 2.4000e+01]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 3.9690e+02 9.1400e+00 2.1600e+01]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 3.9283e+02 4.0300e+00 3.4700e+01]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 5.6400e+00 2.3900e+01]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 3.9345e+02 6.4800e+00 2.2000e+01]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 3.9690e+02 7.8800e+00 1.1900e+01]]


In [78]:
print('Loads the CSV file from the URL into a NumPy array delimiter="," → CSV format. Skip_header=1 → skips the column names (first row)')

Loads the CSV file from the URL into a NumPy array delimiter="," → CSV format. Skip_header=1 → skips the column names (first row)


In [74]:
data = raw_data[:, :-1]

print(data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [79]:
print('Selects all rows. Selects all columns except the last one. These are the feature variables (inputs)')

Selects all rows. Selects all columns except the last one. These are the feature variables (inputs)


In [75]:
target = raw_data[:, -1]

print(target)

[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.4 21.7 22.8
 18.8 18.7 18.5 18.3 21.2 19.2 20.4 19.3 22.  20.3 20.5 17.3 18.8 21.4
 15.7 16.2 18.  14.3 19.2 19.6 23.  18.4 15.6 18.1 17.4 17.1 13.3 17.8
 14.  14.4 13.4 15.6 11.8 13.8 15.6 14.6 17.8 15.4 21.5 19.6 15.3 19.4
 17.  15.6 13.1 41.3 24.3 23.3 27.  50.  50.  50.  22.7 25.  50.  23.8
 23.8 22.3 17.4 19.1 23.1 23.6 22.6 29.4 23.2 24.6 29.9 37.2 39.8 36.2
 37.9 32.5 26.4 29.6 50.  32.  29.8 34.9 37.  30.5 36.4 31.1 29.1 50.
 33.3 3

In [80]:
print('Selects all rows. Selects the last column only. This is the target variable (output, e.g. house price)')

Selects all rows. Selects the last column only. This is the target variable (output, e.g. house price)


In [76]:
housing_data = data

print(housing_data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [81]:
print('Assigns the feature data to a new variable name. housing_data and data now reference the same array')

Assigns the feature data to a new variable name. housing_data and data now reference the same array
